version: '3.1'

services:
  postgres_db:
    container_name: bookshop_db
    image: 'postgres:16'
    environment:
      POSTGRES_DB: shop
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
    ports:
      - "5532:5432"
